spring:
  application:
    name: CodeJourney-CoLab-Backend
  datasource:
    url: jdbc:mysql://47.103.88.59:3306/colab
    # *改成你自己的本地数据库用户名和密码！
    username: zwj
    password: PY823KtdFRKWmpww
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: codejourneycolab#secret*key-wohenshenmiwohenshenmi
  expiration: 604800000

server:
  port: 8048

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tongji.codejourneycolab.codejourneycolabbackend.entity

sharedb:
  openDocumentUrl: http://127.0.0.1:4242/share/opendocument
  getUserUrl: http://127.0.0.1:4242/share/getUsersByDocCode

redis:
  host: localhost
  port: 6379